server:
  port: ${PORT:8081}
  # address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: kolposkopija
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages/messages

# Business logic vars
bslgc:
  rate: 20
  commission: 1.25
  hours: 182

bezkoder:
  openapi:
    dev-url: http://localhost:8081
    prod-url: http://localhost:8081

bbs:
  bens:
    - id: valstskase_1
      ben-name: Valsts budžets (VID)
      ben-address:
      ben-acc-no: LV33TREL1060000300000
      ben-legal-id: 90000010008
      ben-country: LV
      bb-name: Valsts kase
      bb-address: Smilšu ielā 1, Rīgā, LV-1919
      bb-swift: TRELLV22
    - id: psd
      ben-name: PSD, SIA
      ben-address: Rīga, Tallinas iela 30A - 37, Latvija
      ben-acc-no: LV10HABA0551009218135
      ben-legal-id: 40003725708
      ben-country: LV
      bb-name: Swedbank, AS
      bb-address: Balasta dambis 1a, Rīga, LV-1048
      bb-swift: HABALV22
